---
- name: Demo on Play level variables
  hosts: localhost
  vars:
    URLS:
      - URL1: play.example.com
        demo: Google
      - URL2: play2.example.com
        demo: Yahoo
  vars_files:
    exvars.yml
  tasks:
    - name: Print URL froom play level variable
      ansible.builtin.debug:
        msg: URL2 - {{ URLS[1] }}

    - name: Print from task level
      vars:
        Company: Google
      ansible.builtin.debug:
        msg: "{{ Company }}"

    - name: print from a file
      ansible.builtin.debug:
        msg: City - {{ City }}
    - name: load from role
      roles:
        - sample 

- name: print from role
  hosts: localhost
  roles:
    - sample
      
