---
- name: Demo on Play level variables
  hosts: localhost
  vars:
    URLS:
      - URL1: play.example.com
        demo: Google
      - URL2: play2.example.com
        demo: Yahoo
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL2 - {{ URLS[1] }}
    - name: define task level variables
      vars:
        Company: Google
      ansible.builtin.debug:
        msg: {{ Company }}
